modLoader="javafml"
loaderVersion="[40,)"
license="GPL3"

[[mods]]
    modId="tacz"
    version="${file.jarVersion}"
    displayName="Timeless and Classics Guns: Zero"
    updateJSONURL=""
    displayURL=""
    authors="Serene Wave Studio | Timeless Squad"
    description='''
'''

[[dependencies.tacz]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tacz]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"